language: java
jdk:
- oraclejdk7
install:
- true
#before_script:
#- export http_proxy='http://public-proxy1-0-crd.data.sfdc.net:8080'
#- export https_proxy='http://public-proxy1-0-crd.data.sfdc.net:8080'
script:

# 1 - Creates snapshot jars containing dev changes. 
- mvn clean install -Dhttp.proxyHost=public-proxy1-0-crd.data.sfdc.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts="*.salesforce.com|10.*" -Dmaven.wagon.http.ssl.insecure=true --settings ./.travis/settings.xml
#- mvn clean install -DproxySet=true -DproxyHost=public-proxy1-0-crd.data.sfdc.net -DproxyPort=8080 --settings ./.travis/settings.xml

# 2a - Runs Aura integration tests on master branch.
- mvn post-integration-test -Pubuntu12 -Pdesktop -DskipJsDoc -DskipUnitTests -DrunIntTests -DtestThreadCount=2 -Dwebdriver.browser.type=GOOGLECHROME -Dwebdriver.reusebrowser=true -Dwebdriver.timeout.getdriver=90 -Dwebdriver.timeout.getdriver=30
